### PR TITLE
a fix and a url update

### PR DESCRIPTION
**Pull request by juhp**
- fix dates in blog archive list to not be for current displayed post
- update url to stackage readme section on adding package
- bump to final lts-22.43

### CODE REVIEW

**Comment by chreekat** [comment]
Nice, thanks. :) I'll work on getting this deployed, which is still a bit of a bad process.

**Comment by chreekat** [comment]
@juhp fyi I'm downgrading back to lts-22.6 for operational reasons.

The app is built and run on NixOS, so I prefer to choose LTSs that are available on that operating system.

Since we haven't bumped to nixos-24.11 yet, the latest available ghc-9.6 is ghc-9.6.3, which means lts-22.6.

**Comment by chreekat** [comment]
I'd like to bump everything to nixos-24.11, which has a lot more options. https://search.nixos.org/packages?channel=24.11&from=0&size=50&sort=relevance&type=packages&query=haskell.compiler.

**Comment by juhp** [comment]
Thanks

**Comment by chreekat** [comment]
Finally deployed now. :)

**Pull request merged**
